# Generated by Django 5.0.1 on 2024-01-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(verbose_name='max_lenght=255')),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
