# Generated by Django 5.0.1 on 2024-01-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuarios',
            new_name='id_usuario',
        ),
    ]
